# Generated by Django 2.0.1 on 2019-09-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_name',
            name='icon',
            field=models.ImageField(upload_to='site_icon'),
        ),
    ]
