# Generated by Django 2.0.1 on 2019-09-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_auto_20190927_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='icon_food',
            field=models.ImageField(upload_to='main_icon'),
        ),
    ]
