# Generated by Django 2.0.1 on 2019-09-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_auto_20190927_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='food',
        ),
        migrations.AddField(
            model_name='main',
            name='food_count',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
    ]
